### ISSUE TITLE
Consider using events for engine core instead of explicit method calls

### ISSUE THREAD

**Issue by kitskub** [flowpowered/engine#10]
If we used events for core events (EngineStart, EngineStop, etc.?) then we could remove duplicate stuff in FlowSingleplayerImpl.

Upsides:
- Modularization
- Perhaps cleaner code

Downsides:
- Events are slightly slower (isn't a real problem because enginestart/stop only happens once
- Will need to still have a way to register the events

**Comment by olliestanley** [comment]
I like this idea - the less duplicate code the better.

**Comment by Wolf480pl** [comment]
Sounds cool, just make sure nobody accidentally starts an already started engine.

**Comment by dredhorse** [comment]
+1 from me too

**Comment by Zidane** [comment]
Events are definitely the way to go.

You've saw how I use them in Ember and it works well :p.

**Comment by Grinch** [comment]
I agree with the rest of you. :p

**Comment by kitskub** [comment]
Did not make the core events, but did modularize: 
0de7e37395530ae02cc5fafa39c97b4a63ac9630
