### ISSUE TITLE
Don't hide React behind a Physics API (Discussion)

### ISSUE THREAD

**Issue by kitskub** [flowpowered/engine#4]
Ok, so this is up for discussion: @DDoS @Wolf480pl 

So, in Spout, the idea was to hide the physics implementation behind a generic physics API. This was supposed to allow for the physics implementation to change at will. However, there is a reason for version control: we don't have to update to a new React unless we want to. (React is under version control, right @DDoS). And, by exposing React, we allow for so many more possiblities than with a physics API which will probably lag behind.

**Comment by Wolf480pl** [comment]
I can see one problem: flow-math is immutable, and React uses mutable vectors.

**Comment by olliestanley** [comment]
Does a generic API make it easier for developers writing for the platform? If so, how much easier?

**Comment by kitskub** [comment]
@Wolf480pl the point is we'd still have the ReactConverter stuff in math. But yes, that is a small oddity.

@DziNeIT it CAN. However, especially with React's latest update, much of the PhysicsComponent doesn't take advantage of the latest changes. And seeing as we don't really have a "team" to devote just to keeping the physics stuff updated/clean, it will lag behind and make things messy.

**Comment by olliestanley** [comment]
@kitskub If the added ease for the developer comes with the consequence of not being able to provide up-to-date versions of React without a whole load of effort then I'm with you on this one. Like you say, it would be plausible if you had a big team but that's just not the case.

**Comment by kitskub** [comment]
Alright, @Wolf480pl do you have a better/different idea?

**Comment by DDoS** [comment]
React isn't versioned right now, but the upstream is, so it would be easy to do, just follow that.  
I don't see any reason why React would need an API over it. Unlike certain things, such as graphics, it should work on all platform consistently (since it doesn't have any dependencies, graphics on the other hand depend on OpenGL, which varies often between 2.0 and 3.2).  
The math is the only annoying thing to deal with since we're dealing with different classes, but the conventions are mostly the same.

**Comment by Zidane** [comment]
@DDoS 

Is your plan to ever switch React to immutable vectors or is that borderline unrealistic?

**Comment by kitskub** [comment]
@Zidane 

I'm pretty sure that it was decided to keep React using mutable vectors to keep the diff from the upstream as small as possible as well as decrease the performance hindrance from object creation.

**Comment by kitskub** [comment]
Comments: https://github.com/flow/flow-engine/tree/nophysicsapi

**Comment by DDoS** [comment]
@kitskub Right, except React doesn't make use that much of the mutability of the vectors to reuse them, but it does so in a few key areas that makes switching really difficult.  
I actually tried debugging the last attempt for 1 week before giving up, having made no progress.

**Comment by kitskub** [comment]
In current now
